source("cachematrix.R")
print("############ Create an N rows X N columns matrix. N is set to 5") 
print("############ Populate the matrix with N*N values got from a normal distribution with N*N as mean and 3*N as standard deviation.") 
print("############ Print the created matrix")
n<-5
M<-matrix(rnorm(n*n,n*n,3*n),n,n)
print(M)
print("############ Invoke makeCacheMatrix function. A list is returned and assigned to variable cm") 
cm<-makeCacheMatrix()
## print(cm)
print("############ Invoke get function on cm list, the empty matrix is returned")
out<-cm$get()
print(out)
print("############ Save the previously created matrix with set function on cm list")
cm$set(M)
print("############ Invoke get function on cm list, the saved matrix is returned")
out<-cm$get()
print(out)
print("############ Invoke getinverse function on cm list, the empty matrix is returned")
IM<-cm$getinverse()
print(IM)
print("############ Invoke cacheSolve function to invert the matrix. Print the returned inverted matrix")
IM<-cacheSolve(cm)
print(IM)
print("############ Invoke cacheSolve function to invert the matrix. No calculation is done, the cached matrix is returned.")
IM<-cacheSolve(cm)
print("############ Print the returned inverted matrix")
print(IM)
print("############ Save the inverted matrix with setinverse function on cm list")
cm$setinverse(IM)
print("############ Get the inverted matrix with getinverse function on cm list. Print it")
out<-cm$getinverse()
print(out)
